#mengmeng wu
#merge ny census data

data is too big to upload to github
can be accessed via:
https://drive.google.com/file/d/1vaO21FvTOWQkQd52CZI9DHawTCoWaMST/view?usp=drive_link

In [34]:
import pandas as pd

dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]


common_columns = list(dfs[0].columns)
for df in dfs[1:]:
    common_columns = [col for col in common_columns if col in df.columns]


for i in range(len(dfs)):
    dfs[i] = dfs[i][common_columns]


final_df = pd.concat(dfs, axis=0, ignore_index=True)

/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,32,33,34,35,36,37,92,93,94,95,96,97,110,111,112,113,114,115,128,129,130,131,132,133,146,147,148,149,150,151) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,32,33,34,35,36,37,92,93,94,95,96,97,110,111,112,113,114,115,128,129,130,131,132,133,146,147,148,149,150,151) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,6,7,10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,70,71,74,75,78,79,82,83,86,87,90,91,94,95,98,99,102,103,106,107,110,111,114,115,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,234,235,238,239,242,243,246,247,250,251,254,255,258,259,262,263,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,326,327,330,331,334,335,338,339,342,343,346,347,350,351,354,355,358,359,362,363,366,367,370,371,374,375,378,379,382,383,386,387,390,391,394,395,398,399,402,403,406,407,410,411,414,415,418,419,422,423,426,427,430,431,434,435,438,439,442,443,446,447,450,451,454,455,458,459,462,463,466,467,470,471,474,475,478,479,482,483,486,487,490,491,494,495,498,499,502,503,506,507,510,511,514,515,518,519,522,523,526,527,530,531,534,535,538,539,542,543,546,547,550,551,554,555,558,559,562,563,566,567,570,571,574,575,578,579,582,583,586,587,590,591,594,595,598,599,602,603,606,607,610,611,614,615,618,619,622,623,626,627,630,631,634,635,638,639,642,643,646,647) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,6,7,10,11,14,15,18,19,22,23,26,27,30,31,34,35,38,39,42,43,46,47,50,51,54,55,58,59,62,63,66,67,70,71,74,75,78,79,82,83,86,87,90,91,94,95,98,99,102,103,106,107,110,111,114,115,118,119,122,123,126,127,130,131,134,135,138,139,142,143,146,147,150,151,154,155,182,183,186,187,190,191,194,195,198,199,202,203,206,207,210,211,214,215,218,219,222,223,226,227,230,231,234,235,238,239,242,243,246,247,250,251,254,255,258,259,262,263,266,267,270,271,274,275,278,279,282,283,286,287,290,291,294,295,298,299,302,303,306,307,310,311,314,315,318,319,322,323,326,327,330,331,334,335,338,339,342,343,346,347,350,351,354,355,358,359,362,363,366,367,370,371,374,375,378,379,382,383,386,387,390,391,394,395,398,399,402,403,406,407,410,411,414,415,418,419,422,423,426,427,430,431,434,435,438,439,442,443,446,447,450,451,454,455,458,459,462,463,466,467,470,471,474,475,478,479,482,483,486,487,490,491,494,495,498,499,502,503,506,507,510,511,514,515,518,519,522,523,526,527,530,531,534,535,538,539,542,543,546,547,550,551,554,555,558,559,562,563,566,567,570,571,574,575,578,579,582,583,586,587,590,591,594,595,598,599,602,603,606,607,610,611,614,615,618,619,622,623,626,627,630,631,634,635,638,639,642,643,646,647) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,132,133,136,137,142,143,146,147,152,153,156,157,162,163,166,167,172,173,176,177,182,183,186,187,192,193,196,197,202,203,206,207,212,213,216,217,222,223,226,227,232,233,236,237,242,243,246,247,252,253,256,257,282,283,286,287,292,293,296,297,302,303,306,307,312,313,316,317,322,323,326,327,332,333,336,337,342,343,346,347,352,353,356,357,362,363,366,367,372,373,376,377,382,383,386,387,392,393,396,397,402,403,406,407,412,413,416,417,422,423,426,427,432,433,436,437,442,443,446,447,452,453,456,457,462,463,466,467,472,473,476,477,482,483,486,487,492,493,496,497,502,503,506,507,512,513,516,517,522,523,526,527,532,533,536,537,542,543,546,547,552,553,556,557,562,563,566,567,572,573,576,577,582,583,586,587,592,593,596,597,602,603,606,607,612,613,616,617,622,623,626,627,632,633,636,637,642,643,646,647,652,653,656,657,662,663,666,667) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/1971829629.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1501-Data.csv").iloc[1:] for i in range(13, 24)]

In [36]:
final_df.shape

(56055, 230)

In [37]:
final_df.head()

,GEO_ID,NAME,S1501_C01_001E,S1501_C01_001M,S1501_C02_001E,S1501_C02_001M,S1501_C03_001E,S1501_C03_001M,S1501_C01_002E,S1501_C01_002M,...,S1501_C02_037E,S1501_C02_037M,S1501_C03_037E,S1501_C03_037M,S1501_C01_038E,S1501_C01_038M,S1501_C02_038E,S1501_C02_038M,S1501_C03_038E,S1501_C03_038M
0,1400000US36001000100,"Census Tract 1, Albany County, New York",238,148,105,74,133,128,16.8,15.7,...,-,**,48431,808,12.3,(X),(X),(X),(X),(X)
1,1400000US36001000200,"Census Tract 2, Albany County, New York",789,231,433,166,356,148,24.7,13.6,...,-,**,104750,61511,1.2,(X),(X),(X),(X),(X)
2,1400000US36001000300,"Census Tract 3, Albany County, New York",696,237,473,192,223,145,15.2,12.9,...,61065,20879,50524,23286,2.9,(X),(X),(X),(X),(X)
3,1400000US36001000401,"Census Tract 4.01, Albany County, New York",92,71,63,54,29,43,29.3,35.7,...,74688,50827,48750,9888,7.7,(X),(X),(X),(X),(X)
4,1400000US36001000403,"Census Tract 4.03, Albany County, New York",949,398,285,188,664,298,1.6,2.8,...,70568,22568,70179,28997,6.9,(X),(X),(X),(X),(X)

In [42]:
dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]

common_columns = list(dfs[0].columns)
for df in dfs[1:]:
    common_columns = [col for col in common_columns if col in df.columns]


for i in range(len(dfs)):
    dfs[i] = dfs[i][common_columns]


final_df2 = pd.concat(dfs, axis=0, ignore_index=True)

/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,110,111,148,149) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,138,139,214,215) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,110,111,148,149) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,110,111,148,149) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,110,111,148,149) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,110,111,148,149) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]
/var/folders/3y/pp5rq62s315dq6zz6hm6ywg40000gn/T/ipykernel_81406/2013804318.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,110,111,148,149) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(f"ACSST5Y20{i}.S1903-Data.csv").iloc[1:] for i in range(13, 24)]

In [43]:
final_df2.shape

(56055, 122)

In [44]:
final_df2.head()

,GEO_ID,NAME,S1903_C01_001E,S1903_C01_001M,S1903_C02_001E,S1903_C02_001M,S1903_C01_002E,S1903_C01_002M,S1903_C02_002E,S1903_C02_002M,...,S1903_C02_028E,S1903_C02_028M,S1903_C01_029E,S1903_C01_029M,S1903_C02_029E,S1903_C02_029M,S1903_C01_030E,S1903_C01_030M,S1903_C02_030E,S1903_C02_030M
0,1400000US36001000100,"Census Tract 1, Albany County, New York",800,90,35900,11519,36.6,8.2,27292,9094,...,(X),(X),50.0,(X),(X),(X),35.1,(X),(X),(X)
1,1400000US36001000200,"Census Tract 2, Albany County, New York",2209,213,20665,4142,17.7,5.7,29082,12144,...,(X),(X),31.6,(X),(X),(X),25.5,(X),(X),(X)
2,1400000US36001000300,"Census Tract 3, Albany County, New York",2455,191,35951,8746,62.2,6.8,40927,9284,...,(X),(X),51.8,(X),(X),(X),23.5,(X),(X),(X)
3,1400000US36001000401,"Census Tract 4.01, Albany County, New York",1023,82,71921,6952,95.4,3.6,72905,9051,...,(X),(X),25.1,(X),(X),(X),28.2,(X),(X),(X)
4,1400000US36001000403,"Census Tract 4.03, Albany County, New York",2260,163,50952,13933,70.9,7.9,67222,14376,...,(X),(X),23.7,(X),(X),(X),32.1,(X),(X),(X)

In [48]:
merged_df_ny = pd.merge(final_df, final_df2,
                    on='GEO_ID', 
                    how='inner')

In [49]:
merged_df_ny.shape

(574469, 351)

In [50]:
merged_df_ny.to_csv('ny_census.csv', index=False)